---
page_title: "arubacloud_kmip"
subcategory: "Security"
description: |-
  Retrieves an ArubaCloud Kmip Instance.
---

# arubacloud_kmip

Reads an existing ArubaCloud KMIP instance.

```terraform
data "arubacloud_kmip" "basic" {
  id = "your-kmip-id"
}

output "kmip_name" {
  value = data.arubacloud_kmip.basic.name
}
output "kmip_description" {
  value = data.arubacloud_kmip.basic.description
}
output "kmip_endpoint" {
  value = data.arubacloud_kmip.basic.endpoint
}
```


## Schema

<!-- schema generated by tfplugindocs -->
## Schema


### Arguments

The following arguments are supported:

#### Required

- `id` (String) KMIP identifier (typically the name)
- `kms_id` (String) ID of the associated KMS instance
- `project_id` (String) ID of the project this KMIP belongs to

### Attributes Reference

In addition to all arguments above, the following attributes are exported:

#### Read-Only

- `creation_date` (String) KMIP service creation date
- `deletion_date` (String) KMIP service deletion date
- `name` (String) Name of the KMIP service
- `status` (String) KMIP service status
- `type` (String) KMIP service type


