// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Arubacloud/sdk-go/internal/ports/auth (interfaces: TokenRepository)
//
// Generated by this command:
//
//	mockgen -package memory -destination=zz_mock_auth_test.go github.com/Arubacloud/sdk-go/internal/ports/auth TokenRepository
//

// Package memory is a generated GoMock package.
package memory

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	auth "github.com/Arubacloud/sdk-go/internal/ports/auth"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// FetchToken mocks base method.
func (m *MockTokenRepository) FetchToken(ctx context.Context) (*auth.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchToken", ctx)
	ret0, _ := ret[0].(*auth.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchToken indicates an expected call of FetchToken.
func (mr *MockTokenRepositoryMockRecorder) FetchToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchToken", reflect.TypeOf((*MockTokenRepository)(nil).FetchToken), ctx)
}

// SaveToken mocks base method.
func (m *MockTokenRepository) SaveToken(ctx context.Context, token *auth.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockTokenRepositoryMockRecorder) SaveToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockTokenRepository)(nil).SaveToken), ctx, token)
}
