// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Arubacloud/sdk-go/internal/ports/interceptor (interfaces: Interceptable)
//
// Generated by this command:
//
//	mockgen -package standard -destination=zz_mock_interceptor_test.go github.com/Arubacloud/sdk-go/internal/ports/interceptor Interceptable
//

// Package standard is a generated GoMock package.
package standard

import (
	reflect "reflect"

	interceptor "github.com/Arubacloud/sdk-go/internal/ports/interceptor"
	gomock "go.uber.org/mock/gomock"
)

// MockInterceptable is a mock of Interceptable interface.
type MockInterceptable struct {
	ctrl     *gomock.Controller
	recorder *MockInterceptableMockRecorder
	isgomock struct{}
}

// MockInterceptableMockRecorder is the mock recorder for MockInterceptable.
type MockInterceptableMockRecorder struct {
	mock *MockInterceptable
}

// NewMockInterceptable creates a new mock instance.
func NewMockInterceptable(ctrl *gomock.Controller) *MockInterceptable {
	mock := &MockInterceptable{ctrl: ctrl}
	mock.recorder = &MockInterceptableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterceptable) EXPECT() *MockInterceptableMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockInterceptable) Bind(interceptFuncs ...interceptor.InterceptFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range interceptFuncs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Bind", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockInterceptableMockRecorder) Bind(interceptFuncs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockInterceptable)(nil).Bind), interceptFuncs...)
}
