// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Arubacloud/sdk-go/internal/impl/auth/credentialsrepository/vault (interfaces: VaultClient,LogicalAPI,KvAPI)
//
// Generated by this command:
//
//	mockgen -package vault -destination=zz_mock_vault_test.go github.com/Arubacloud/sdk-go/internal/impl/auth/credentialsrepository/vault VaultClient,LogicalAPI,KvAPI
//

// Package vault is a generated GoMock package.
package vault

import (
	context "context"
	reflect "reflect"

	api "github.com/hashicorp/vault/api"
	gomock "go.uber.org/mock/gomock"
)

// MockVaultClient is a mock of VaultClient interface.
type MockVaultClient struct {
	ctrl     *gomock.Controller
	recorder *MockVaultClientMockRecorder
	isgomock struct{}
}

// MockVaultClientMockRecorder is the mock recorder for MockVaultClient.
type MockVaultClientMockRecorder struct {
	mock *MockVaultClient
}

// NewMockVaultClient creates a new mock instance.
func NewMockVaultClient(ctrl *gomock.Controller) *MockVaultClient {
	mock := &MockVaultClient{ctrl: ctrl}
	mock.recorder = &MockVaultClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultClient) EXPECT() *MockVaultClientMockRecorder {
	return m.recorder
}

// KVv2 mocks base method.
func (m *MockVaultClient) KVv2(mount string) KvAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KVv2", mount)
	ret0, _ := ret[0].(KvAPI)
	return ret0
}

// KVv2 indicates an expected call of KVv2.
func (mr *MockVaultClientMockRecorder) KVv2(mount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KVv2", reflect.TypeOf((*MockVaultClient)(nil).KVv2), mount)
}

// Logical mocks base method.
func (m *MockVaultClient) Logical() LogicalAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logical")
	ret0, _ := ret[0].(LogicalAPI)
	return ret0
}

// Logical indicates an expected call of Logical.
func (mr *MockVaultClientMockRecorder) Logical() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logical", reflect.TypeOf((*MockVaultClient)(nil).Logical))
}

// SetNamespace mocks base method.
func (m *MockVaultClient) SetNamespace(namespace string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNamespace", namespace)
}

// SetNamespace indicates an expected call of SetNamespace.
func (mr *MockVaultClientMockRecorder) SetNamespace(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNamespace", reflect.TypeOf((*MockVaultClient)(nil).SetNamespace), namespace)
}

// SetToken mocks base method.
func (m *MockVaultClient) SetToken(token string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToken", token)
}

// SetToken indicates an expected call of SetToken.
func (mr *MockVaultClientMockRecorder) SetToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockVaultClient)(nil).SetToken), token)
}

// MockLogicalAPI is a mock of LogicalAPI interface.
type MockLogicalAPI struct {
	ctrl     *gomock.Controller
	recorder *MockLogicalAPIMockRecorder
	isgomock struct{}
}

// MockLogicalAPIMockRecorder is the mock recorder for MockLogicalAPI.
type MockLogicalAPIMockRecorder struct {
	mock *MockLogicalAPI
}

// NewMockLogicalAPI creates a new mock instance.
func NewMockLogicalAPI(ctrl *gomock.Controller) *MockLogicalAPI {
	mock := &MockLogicalAPI{ctrl: ctrl}
	mock.recorder = &MockLogicalAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogicalAPI) EXPECT() *MockLogicalAPIMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockLogicalAPI) Write(path string, data map[string]any) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", path, data)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockLogicalAPIMockRecorder) Write(path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockLogicalAPI)(nil).Write), path, data)
}

// MockKvAPI is a mock of KvAPI interface.
type MockKvAPI struct {
	ctrl     *gomock.Controller
	recorder *MockKvAPIMockRecorder
	isgomock struct{}
}

// MockKvAPIMockRecorder is the mock recorder for MockKvAPI.
type MockKvAPIMockRecorder struct {
	mock *MockKvAPI
}

// NewMockKvAPI creates a new mock instance.
func NewMockKvAPI(ctrl *gomock.Controller) *MockKvAPI {
	mock := &MockKvAPI{ctrl: ctrl}
	mock.recorder = &MockKvAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKvAPI) EXPECT() *MockKvAPIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockKvAPI) Get(ctx context.Context, path string) (*api.KVSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path)
	ret0, _ := ret[0].(*api.KVSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKvAPIMockRecorder) Get(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKvAPI)(nil).Get), ctx, path)
}
