---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "arubacloud_key Resource - ArubaCloud"
subcategory: ""
description: |-
  Key resource for KMS
---

# arubacloud_key (Resource)

Key resource for KMS

## Example Usage

```terraform
terraform {
  required_providers {
    arubacloud = {
      source = "aruba/arubacloud"
    }
  }
}

# Create a project
resource "arubacloud_project" "example" {
  name        = "security-project"
  description = "Project for KMS and encryption keys"
}

# Create a KMS instance
resource "arubacloud_kms" "example" {
  name           = "production-kms"
  project_id     = arubacloud_project.example.id
  location       = "ITBG-Bergamo"
  billing_period = "Hour"
  tags           = ["production", "encryption"]
}

# Create an encryption key for AES
resource "arubacloud_key" "aes_key" {
  name       = "aes-encryption-key"
  project_id = arubacloud_project.example.id
  kms_id     = arubacloud_kms.example.id
  algorithm  = "Aes"
}

# Create an RSA key for asymmetric encryption
resource "arubacloud_key" "rsa_key" {
  name       = "rsa-encryption-key"
  project_id = arubacloud_project.example.id
  kms_id     = arubacloud_kms.example.id
  algorithm  = "Rsa"
}

# Output the key IDs
output "aes_key_id" {
  value       = arubacloud_key.aes_key.id
  description = "The ID of the AES encryption key"
}

output "rsa_key_id" {
  value       = arubacloud_key.rsa_key.id
  description = "The ID of the RSA encryption key"
}
```

<!-- schema generated by tfplugindocs -->
## Schema


### Arguments

The following arguments are supported:

#### Required

- `algorithm` (String) Encryption algorithm (e.g., Aes, Rsa)
- `kms_id` (String) ID of the associated KMS
- `name` (String) Key name
- `project_id` (String) ID of the project this Key belongs to

#### Optional

- `description` (String) Key description - optional, not returned by API
- `size` (Number) Key size in bits (e.g., 256, 2048) - optional, not returned by API

### Attributes Reference

In addition to all arguments above, the following attributes are exported:

#### Read-Only

- `id` (String) Key identifier
- `status` (String) Key status - computed, not returned by API in v0.1.18
- `uri` (String) Key URI
