// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Arubacloud/sdk-go/internal/ports/auth (interfaces: CredentialsRepository)
//
// Generated by this command:
//
//	mockgen -package memory -destination=zz_mock_auth_test.go github.com/Arubacloud/sdk-go/internal/ports/auth CredentialsRepository
//

// Package memory is a generated GoMock package.
package memory

import (
	context "context"
	reflect "reflect"

	auth "github.com/Arubacloud/sdk-go/internal/ports/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialsRepository is a mock of CredentialsRepository interface.
type MockCredentialsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialsRepositoryMockRecorder is the mock recorder for MockCredentialsRepository.
type MockCredentialsRepositoryMockRecorder struct {
	mock *MockCredentialsRepository
}

// NewMockCredentialsRepository creates a new mock instance.
func NewMockCredentialsRepository(ctrl *gomock.Controller) *MockCredentialsRepository {
	mock := &MockCredentialsRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepository) EXPECT() *MockCredentialsRepositoryMockRecorder {
	return m.recorder
}

// FetchCredentials mocks base method.
func (m *MockCredentialsRepository) FetchCredentials(ctx context.Context) (*auth.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCredentials", ctx)
	ret0, _ := ret[0].(*auth.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCredentials indicates an expected call of FetchCredentials.
func (mr *MockCredentialsRepositoryMockRecorder) FetchCredentials(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCredentials", reflect.TypeOf((*MockCredentialsRepository)(nil).FetchCredentials), ctx)
}
